#!/bin/sh

if [ "$1" = "start" ]
then
	KERNELRELEASE=$(uname -r)

	rmmod hynitron_touch
	rmmod spi_gpio
	rmmod spi_bitbang
	rmmod i2c_gpio
	rmmod i2c_algo_bit

	. /etc/profile
	printf "load kernel module: "
	cd /mnt/system/ko/
	for ko in ${KERNELRELEASE}/*.ko ; do
		if [ -e $ko ]; then
			km=`basename $ko`
			rm -f $km
			ln -s $ko $km
		fi
	done
	mkdir -p 3rd
	for ko in ${KERNELRELEASE}/3rd/*.ko ; do
		if [ -e $ko ]; then
			km=`basename $ko`
			rm -f 3rd/$km
			ln -s ../$ko 3rd/$km
		fi
	done
	insmod soph_sys.ko
	insmod soph_base.ko
	# insmod soph_rtos_cmdqu.ko
	# insmod soph_fast_image.ko
	# insmod soph_mipi_rx.ko
	# insmod soph_snsr_i2c.ko
	# insmod soph_vi.ko
	# insmod soph_vpss.ko
	# insmod soph_dwa.ko
	# insmod soph_vo.ko
#	insmod soph_mipi_tx.ko
	# insmod soph_rgn.ko
#	insmod soph_wdt.ko
#	insmod soph_clock_cooling.ko
	insmod soph_tpu.ko
	# insmod soph_vcodec.ko
	# insmod soph_jpeg.ko
	# insmod soph_vc_driver.ko MaxVencChnNum=9 MaxVdecChnNum=9
#	insmod soph_rtc.ko
	# insmod soph_ive.ko
	insmod soph_mon.ko
#	insmod soph_pwm.ko
#	insmod soph_saradc.ko
	insmod soph_wiegand.ko
	echo "OK"
	exit 0
fi
